#!/usr/bin/env python3
"""Generate src/regex/unicode_scripts.rs from the Unicode Character Database.

Usage: generate-unicode-scripts.py Scripts.txt PropertyValueAliases.txt

The table lists every maximal run of code points that share one Script
value, sorted by code point; code points without a run have the Unknown
script. Names are emitted in PCRE's loose-matching form (lowercase, without
underscores, hyphens or spaces) so `\\p{Old_Italic}`, `\\p{olditalic}` and the
`\\p{Ital}` alias all select the same script.
"""
import re
import sys


def loose(name):
    return re.sub(r"[ _-]", "", name).lower()


def main():
    scripts_path, aliases_path = sys.argv[1:3]
    version = "unknown"
    runs = []
    with open(scripts_path, encoding="utf-8") as handle:
        for line in handle:
            if line.startswith("# Scripts-"):
                version = line.split("-", 1)[1].split(".txt")[0].strip()
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            code_points, script = [part.strip() for part in line.split(";")]
            if ".." in code_points:
                first, last = code_points.split("..")
            else:
                first = last = code_points
            runs.append((int(first, 16), int(last, 16), script))
    runs.sort()
    merged = []
    for first, last, script in runs:
        if merged and merged[-1][2] == script and merged[-1][1] + 1 == first:
            merged[-1] = (merged[-1][0], last, script)
        else:
            merged.append((first, last, script))
    names = sorted({script for _, _, script in runs} | {"Unknown"})
    aliases = []
    with open(aliases_path, encoding="utf-8") as handle:
        for line in handle:
            line = line.split("#", 1)[0].strip()
            if not line.startswith("sc ;"):
                continue
            parts = [part.strip() for part in line.split(";")]
            long_name = parts[2]
            if long_name not in names:
                continue
            for alias in [parts[1]] + parts[3:]:
                if loose(alias) != loose(long_name):
                    aliases.append((loose(alias), names.index(long_name)))
    aliases.sort()
    out = sys.stdout
    out.write("//! Unicode Script runs generated by\n")
    out.write("//! `scripts/generate-unicode-scripts.py` from Unicode %s.\n" % version)
    out.write("//! Do not edit by hand.\n\n")
    out.write("/// Script names in loose-matching form, one per index.\n")
    out.write("pub(super) const SCRIPT_NAMES: [&str; %d] = [\n" % len(names))
    for name in names:
        out.write("    \"%s\",\n" % loose(name))
    out.write("];\n\n")
    out.write("/// Loose-form script aliases (mostly ISO 15924 codes) and their index.\n")
    out.write("pub(super) const SCRIPT_ALIASES: &[(&str, u16)] = &[\n")
    for alias, index in aliases:
        out.write("    (\"%s\", %d),\n" % (alias, index))
    out.write("];\n\n")
    out.write("/// The `SCRIPT_NAMES` index of the Unknown script.\n")
    out.write("pub(super) const UNKNOWN_SCRIPT: u16 = %d;\n\n" % names.index("Unknown"))
    out.write("/// `(first, last, script index)` runs of code points with a script.\n")
    out.write("pub(super) const SCRIPT_RUNS: &[(u32, u32, u16)] = &[\n")
    for first, last, script in merged:
        out.write("    (0x%X, 0x%X, %d),\n" % (first, last, names.index(script)))
    out.write("];\n")


if __name__ == "__main__":
    main()
