#!/usr/bin/env python3
r"""Generate Unicode Grapheme_Cluster_Break ranges for PCRE ``\X``.

Usage: generate-unicode-grapheme-breaks.py GraphemeBreakProperty.txt
"""

import sys


def main():
    path = sys.argv[1]
    ranges = {}
    version = "unknown"
    with open(path, encoding="utf-8") as handle:
        for raw in handle:
            if raw.startswith("# GraphemeBreakProperty-"):
                version = raw.split("-", 1)[1].split(".txt", 1)[0]
            line = raw.split("#", 1)[0].strip()
            if not line or ";" not in line:
                continue
            code_points, name = [part.strip() for part in line.split(";", 1)]
            if ".." in code_points:
                first, last = code_points.split("..")
            else:
                first = last = code_points
            ranges.setdefault(name, []).append((int(first, 16), int(last, 16)))

    names = sorted(ranges)
    out = sys.stdout
    out.write("//! Unicode Grapheme_Cluster_Break ranges generated by\n")
    out.write(
        "//! `scripts/generate-unicode-grapheme-breaks.py` from Unicode %s.\n" % version
    )
    out.write("//! Do not edit by hand.\n\n")
    out.write("pub(super) const GRAPHEME_BREAK_NAMES: [&str; %d] = [\n" % len(names))
    for name in names:
        out.write('    "%s",\n' % name)
    out.write("];\n\n")
    out.write("pub(super) const GRAPHEME_BREAK_RANGES: &[(u32, u32, u8)] = &[\n")
    entries = sorted(
        (first, last, index, name)
        for index, name in enumerate(names)
        for first, last in ranges[name]
    )
    for first, last, index, name in entries:
        out.write("    (0x%X, 0x%X, %d), // %s\n" % (first, last, index, name))
    out.write("];\n")


if __name__ == "__main__":
    main()
