#!/usr/bin/env python3
r"""Generate the Unicode binary-property subset exposed by PCRE 10.42.

Usage: generate-unicode-binary-properties.py PropertyAliases.txt DATA...

DATA is the matching Unicode PropList, DerivedCoreProperties,
extracted/DerivedBinaryProperties, and emoji/emoji-data files. The accepted
set is intentionally PCRE 10.42's public \p property surface, not every UCD
binary property.
"""

import re
import sys


SUPPORTED = {
    "ASCII_Hex_Digit", "Alphabetic", "Bidi_Control", "Bidi_Mirrored",
    "Cased", "Case_Ignorable", "Changes_When_Casefolded",
    "Changes_When_Casemapped", "Changes_When_Lowercased",
    "Changes_When_Titlecased", "Changes_When_Uppercased", "Dash",
    "Deprecated", "Default_Ignorable_Code_Point", "Diacritic",
    "Emoji_Modifier_Base", "Emoji_Component", "Emoji_Modifier", "Emoji",
    "Emoji_Presentation", "Extender", "Extended_Pictographic",
    "Grapheme_Base", "Grapheme_Extend", "Grapheme_Link", "Hex_Digit",
    "ID_Continue", "Ideographic", "ID_Start", "IDS_Binary_Operator",
    "IDS_Trinary_Operator", "Join_Control", "Logical_Order_Exception",
    "Lowercase", "Math", "Noncharacter_Code_Point", "Pattern_Syntax",
    "Pattern_White_Space", "Prepended_Concatenation_Mark", "Quotation_Mark",
    "Radical", "Regional_Indicator", "Sentence_Terminal", "Soft_Dotted",
    "Terminal_Punctuation", "Unified_Ideograph", "Uppercase",
    "Variation_Selector", "White_Space", "XID_Continue", "XID_Start",
}


def loose(name):
    return re.sub(r"[ _-]", "", name).lower()


def main():
    aliases_path, *data_paths = sys.argv[1:]
    aliases = {}
    with open(aliases_path, encoding="utf-8") as handle:
        in_binary = False
        for raw in handle:
            if raw.startswith("# Binary Properties"):
                in_binary = True
                continue
            if in_binary and raw.startswith("# Total"):
                break
            line = raw.split("#", 1)[0].strip()
            if not in_binary or not line:
                continue
            parts = [part.strip() for part in line.split(";")]
            canonical = parts[1]
            if canonical not in SUPPORTED:
                continue
            for alias in parts:
                aliases[loose(alias)] = canonical

    ranges = {name: [] for name in SUPPORTED}
    version = "unknown"
    for path in data_paths:
        with open(path, encoding="utf-8") as handle:
            for raw in handle:
                if version == "unknown":
                    match = re.search(r"-(\d+\.\d+\.\d+)\.txt", raw)
                    if match:
                        version = match.group(1)
                line = raw.split("#", 1)[0].strip()
                if not line or ";" not in line:
                    continue
                code_points, name = [part.strip() for part in line.split(";", 1)]
                if name not in SUPPORTED:
                    continue
                if ".." in code_points:
                    first, last = code_points.split("..")
                else:
                    first = last = code_points
                ranges[name].append((int(first, 16), int(last, 16)))

    names = sorted(SUPPORTED)
    out = sys.stdout
    out.write("//! Unicode binary-property ranges generated by\n")
    out.write("//! `scripts/generate-unicode-binary-properties.py` from Unicode %s.\n" % version)
    out.write("//! Do not edit by hand.\n\n")
    out.write("pub(super) const BINARY_PROPERTY_NAMES: [&str; %d] = [\n" % len(names))
    for name in names:
        out.write('    "%s",\n' % loose(name))
    out.write("];\n\n")
    out.write(
        "pub(super) const EXTENDED_PICTOGRAPHIC_INDEX: u8 = %d;\n\n"
        % names.index("Extended_Pictographic")
    )
    out.write("pub(super) const BINARY_PROPERTY_ALIASES: &[(&str, u8)] = &[\n")
    for alias, canonical in sorted(aliases.items()):
        out.write('    ("%s", %d),\n' % (alias, names.index(canonical)))
    out.write("];\n\n")
    out.write("pub(super) const BINARY_PROPERTY_RANGES: &[&[(u32, u32)]] = &[\n")
    for name in names:
        merged = []
        for first, last in sorted(ranges[name]):
            if merged and merged[-1][1] + 1 >= first:
                merged[-1] = (merged[-1][0], max(merged[-1][1], last))
            else:
                merged.append((first, last))
        out.write("    &[ // %s\n" % name)
        for first, last in merged:
            out.write("        (0x%X, 0x%X),\n" % (first, last))
        out.write("    ],\n")
    out.write("];\n")


if __name__ == "__main__":
    main()
