#!/usr/bin/env python3
"""Generate PCRE Script_Extensions runs from the Unicode database.

Usage: generate-unicode-script-extensions.py Scripts.txt ScriptExtensions.txt PropertyValueAliases.txt

Characters omitted by ScriptExtensions.txt inherit their ordinary Script
property, so the generated table contains only explicit extension sets. The
indices intentionally use the same sorted long-name order as
generate-unicode-scripts.py.
"""

import re
import sys


def loose(name):
    return re.sub(r"[ _-]", "", name).lower()


def main():
    scripts_path, extensions_path, aliases_path = sys.argv[1:4]
    version = "unknown"
    short_to_long = {}
    names = {"Unknown"}
    with open(aliases_path, encoding="utf-8") as handle:
        for line in handle:
            line = line.split("#", 1)[0].strip()
            if not line.startswith("sc ;"):
                continue
            parts = [part.strip() for part in line.split(";")]
            short_to_long[parts[1]] = parts[2]
    with open(scripts_path, encoding="utf-8") as handle:
        for line in handle:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            _, script = [part.strip() for part in line.split(";")]
            names.add(script)

    raw_runs = []
    with open(extensions_path, encoding="utf-8") as handle:
        for line in handle:
            if line.startswith("# ScriptExtensions-"):
                version = line.split("-", 1)[1].split(".txt")[0].strip()
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            code_points, scripts = [part.strip() for part in line.split(";")]
            if ".." in code_points:
                first, last = code_points.split("..")
            else:
                first = last = code_points
            script_names = tuple(sorted(short_to_long[name] for name in scripts.split()))
            raw_runs.append((int(first, 16), int(last, 16), script_names))

    names = sorted(names)
    indices = {name: index for index, name in enumerate(names)}
    runs = []
    for first, last, scripts in sorted(raw_runs):
        script_indices = tuple(indices[name] for name in scripts)
        if runs and runs[-1][2] == script_indices and runs[-1][1] + 1 == first:
            runs[-1] = (runs[-1][0], last, script_indices)
        else:
            runs.append((first, last, script_indices))

    out = sys.stdout
    out.write("//! Unicode Script_Extensions runs generated by\n")
    out.write("//! `scripts/generate-unicode-script-extensions.py` from Unicode %s.\n" % version)
    out.write("//! Do not edit by hand.\n\n")
    out.write("/// Explicit `(first, last, script indices)` Script_Extensions runs.\n")
    out.write("pub(super) const SCRIPT_EXTENSION_RUNS: &[(u32, u32, &[u16])] = &[\n")
    for first, last, scripts in runs:
        values = ", ".join(str(index) for index in scripts)
        out.write("    (0x%X, 0x%X, &[%s]),\n" % (first, last, values))
    out.write("];\n")


if __name__ == "__main__":
    main()
