#!/usr/bin/env python3
r"""Generate Unicode simple case-fold mappings for PCRE caseless matching.

Usage: generate-unicode-case-folding.py CaseFolding.txt

Only the one-code-point common and simple mappings are used. Full and Turkic
case folds are intentionally excluded because PCRE2's ordinary caseless mode
uses Unicode simple case equivalence, not multi-code-point or locale-specific
folding.
"""

import sys


def main():
    path = sys.argv[1]
    mappings = {}
    version = "unknown"
    with open(path, encoding="utf-8") as handle:
        for raw in handle:
            if raw.startswith("# CaseFolding-"):
                version = raw.split("-", 1)[1].split(".txt", 1)[0]
            line = raw.split("#", 1)[0].strip()
            if not line:
                continue
            code_point, status, mapping, _ = [part.strip() for part in line.split(";", 3)]
            if status not in {"C", "S"}:
                continue
            mapped = mapping.split()
            if len(mapped) == 1:
                mappings[int(code_point, 16)] = int(mapped[0], 16)

    out = sys.stdout
    out.write("//! Unicode simple case-fold mappings generated by\n")
    out.write(
        "//! `scripts/generate-unicode-case-folding.py` from Unicode %s.\n" % version
    )
    out.write("//! Do not edit by hand.\n\n")
    out.write("pub(super) const SIMPLE_CASE_FOLD: &[(u32, u32)] = &[\n")
    for source, target in sorted(mappings.items()):
        out.write("    (0x%X, 0x%X),\n" % (source, target))
    out.write("];\n")


if __name__ == "__main__":
    main()
