#!/usr/bin/env python3
"""Generate src/regex/unicode_categories.rs from the Unicode database.

The table lists every maximal run of assigned code points that share one
General_Category value, sorted by code point. Unassigned code points (Cn)
are implied by gaps.

Usage: generate-unicode-categories.py [UnicodeData.txt VERSION]

Passing the official UnicodeData file and version makes a historical PCRE
table reproducible even when the host Python carries a newer Unicode release.
With no arguments, the host `unicodedata` database is used for convenience.
"""

import sys
import unicodedata

CATEGORIES = [
    "Lu", "Ll", "Lt", "Lm", "Lo",
    "Mn", "Mc", "Me",
    "Nd", "Nl", "No",
    "Pc", "Pd", "Ps", "Pe", "Pi", "Pf", "Po",
    "Sm", "Sc", "Sk", "So",
    "Zs", "Zl", "Zp",
    "Cc", "Cf", "Cs", "Co", "Cn",
]


def python_runs():
    previous = None
    start = 0
    for code_point in range(0x110000):
        category = unicodedata.category(chr(code_point))
        if category != previous:
            if previous is not None and previous != "Cn":
                yield start, code_point - 1, previous
            previous = category
            start = code_point
    if previous != "Cn":
        yield start, 0x10FFFF, previous


def unicode_data_runs(path):
    entries = []
    range_start = None
    range_category = None
    with open(path, encoding="utf-8") as handle:
        for raw in handle:
            fields = raw.rstrip("\n").split(";")
            code_point = int(fields[0], 16)
            name = fields[1]
            category = fields[2]
            if name.endswith(", First>"):
                range_start = code_point
                range_category = category
                continue
            if name.endswith(", Last>"):
                if range_start is None or range_category != category:
                    raise ValueError("malformed UnicodeData First/Last range")
                entries.append((range_start, code_point, category))
                range_start = None
                range_category = None
                continue
            entries.append((code_point, code_point, category))
    if range_start is not None:
        raise ValueError("unterminated UnicodeData First/Last range")

    merged = []
    for first, last, category in entries:
        if category == "Cn":
            continue
        if merged and merged[-1][2] == category and merged[-1][1] + 1 == first:
            merged[-1] = (merged[-1][0], last, category)
        else:
            merged.append((first, last, category))
    return merged


def main():
    if len(sys.argv) == 1:
        version = unicodedata.unidata_version
        generated_runs = python_runs()
    elif len(sys.argv) == 3:
        version = sys.argv[2]
        generated_runs = unicode_data_runs(sys.argv[1])
    else:
        raise SystemExit("usage: generate-unicode-categories.py [UnicodeData.txt VERSION]")

    out = sys.stdout
    out.write("//! Unicode General_Category runs generated by\n")
    out.write("//! `scripts/generate-unicode-categories.py` from Unicode %s.\n" % version)
    out.write("//! Do not edit by hand.\n\n")
    out.write("/// General_Category values in `CATEGORY_NAMES` order.\n")
    out.write("pub(super) const CATEGORY_NAMES: [&str; %d] = [\n" % len(CATEGORIES))
    for name in CATEGORIES:
        out.write("    \"%s\",\n" % name)
    out.write("];\n\n")
    out.write("/// `(first, last, category index)` runs of assigned code points.\n")
    out.write("pub(super) const CATEGORY_RUNS: &[(u32, u32, u8)] = &[\n")
    for start, end, category in generated_runs:
        out.write("    (0x%X, 0x%X, %d),\n" % (start, end, CATEGORIES.index(category)))
    out.write("];\n")


if __name__ == "__main__":
    main()
