#!/usr/bin/env python3
r"""Generate the Bidi_Class table exposed by PCRE 10.42 \p syntax.

Usage: generate-unicode-bidi-classes.py DerivedBidiClass.txt PropertyValueAliases.txt
"""

import sys


def main():
    data_path, aliases_path = sys.argv[1:3]
    classes = []
    with open(aliases_path, encoding="utf-8") as handle:
        for raw in handle:
            line = raw.split("#", 1)[0].strip()
            if not line.startswith("bc ;"):
                continue
            parts = [part.strip() for part in line.split(";")]
            classes.append(parts[1])
    classes = sorted(set(classes))
    ranges = {name: [] for name in classes}
    version = "unknown"
    with open(data_path, encoding="utf-8") as handle:
        for raw in handle:
            if raw.startswith("# DerivedBidiClass-"):
                version = raw.split("-", 1)[1].split(".txt")[0].strip()
            line = raw.split("#", 1)[0].strip()
            if not line or ";" not in line:
                continue
            code_points, name = [part.strip() for part in line.split(";", 1)]
            if name not in ranges:
                continue
            if ".." in code_points:
                first, last = code_points.split("..")
            else:
                first = last = code_points
            ranges[name].append((int(first, 16), int(last, 16)))

    out = sys.stdout
    out.write("//! Unicode Bidi_Class ranges generated by\n")
    out.write("//! `scripts/generate-unicode-bidi-classes.py` from Unicode %s.\n" % version)
    out.write("//! Do not edit by hand.\n\n")
    out.write("pub(super) const BIDI_CLASS_NAMES: [&str; %d] = [\n" % len(classes))
    for name in classes:
        out.write('    "%s",\n' % name.lower())
    out.write("];\n\n")
    out.write("pub(super) const BIDI_CLASS_RANGES: &[&[(u32, u32)]] = &[\n")
    for name in classes:
        out.write("    &[ // %s\n" % name)
        for first, last in ranges[name]:
            out.write("        (0x%X, 0x%X),\n" % (first, last))
        out.write("    ],\n")
    out.write("];\n")


if __name__ == "__main__":
    main()
