#!/usr/bin/env python3
"""Generate src/regex/unicode_categories.rs from the Python Unicode database.

The table lists every maximal run of assigned code points that share one
General_Category value, sorted by code point. Unassigned code points (Cn)
are implied by gaps. Regenerate with a Python whose `unicodedata` module
carries the Unicode version named in the generated header.
"""

import sys
import unicodedata

CATEGORIES = [
    "Lu", "Ll", "Lt", "Lm", "Lo",
    "Mn", "Mc", "Me",
    "Nd", "Nl", "No",
    "Pc", "Pd", "Ps", "Pe", "Pi", "Pf", "Po",
    "Sm", "Sc", "Sk", "So",
    "Zs", "Zl", "Zp",
    "Cc", "Cf", "Cs", "Co", "Cn",
]


def runs():
    previous = None
    start = 0
    for code_point in range(0x110000):
        category = unicodedata.category(chr(code_point))
        if category != previous:
            if previous is not None and previous != "Cn":
                yield start, code_point - 1, previous
            previous = category
            start = code_point
    if previous != "Cn":
        yield start, 0x10FFFF, previous


def main():
    out = sys.stdout
    out.write("//! Unicode General_Category runs generated by\n")
    out.write("//! `scripts/generate-unicode-categories.py` from Unicode %s.\n" % unicodedata.unidata_version)
    out.write("//! Do not edit by hand.\n\n")
    out.write("/// General_Category values in `CATEGORY_NAMES` order.\n")
    out.write("pub(super) const CATEGORY_NAMES: [&str; %d] = [\n" % len(CATEGORIES))
    for name in CATEGORIES:
        out.write("    \"%s\",\n" % name)
    out.write("];\n\n")
    out.write("/// `(first, last, category index)` runs of assigned code points.\n")
    out.write("pub(super) const CATEGORY_RUNS: &[(u32, u32, u8)] = &[\n")
    for start, end, category in runs():
        out.write("    (0x%X, 0x%X, %d),\n" % (start, end, CATEGORIES.index(category)))
    out.write("];\n")


if __name__ == "__main__":
    main()
